//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRequest
    {
        public int CashRequestID { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public Nullable<int> CashRequestStatusID { get; set; }
        public Nullable<int> PaymentFromBankID { get; set; }
        public Nullable<int> PaymentToBankID { get; set; }
        public string RequestDate { get; set; }
        public string ResponseDate { get; set; }
        public string RequestAmount { get; set; }
        public string ResponseAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual CashRequestStatu CashRequestStatu { get; set; }
        public virtual FinancialInstitution FinancialInstitution { get; set; }
        public virtual FinancialInstitution FinancialInstitution1 { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
