//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialInstitution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialInstitution()
        {
            this.CashRequests = new HashSet<CashRequest>();
            this.CashRequests1 = new HashSet<CashRequest>();
        }
    
        public int FinancialInstitutionID { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public string AccountName { get; set; }
        public string NickName { get; set; }
        public string AccountNumber { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionIFSCCode { get; set; }
        public string InstitutionLocation { get; set; }
        public string InstitutionCity { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashRequest> CashRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashRequest> CashRequests1 { get; set; }
    }
}
